### ISSUE TITLE
Octo support

### ISSUE THREAD

**Issue by dreckbaer** [medevil84/FanControl.AquacomputerDevices#1]
First of all, **THANK YOU VERY MUCH** for this build!
I have been waiting for something like this for a long time.

The only problem I have is, that I am not able to use Visual and recompile the files to use my Octo device! I don't know how the software works, I've never learned how to program - so the only response I get from Visual is a bunch of errors and the message "build failed". :(

I would be grateful if you could upload a version which has the Octo enabled for all the people who don't have any idea of programming whatsoever.  

Many thanks in advance!

**Comment by medevil84** [comment]
No problem, please try with the attached file and let me know if it works.
[FanControl.AquacomputerDevices_OCTO_TESTING_v1.0.0.0.zip](https://github.com/medevil84/FanControl.AquacomputerDevices/files/11240335/FanControl.AquacomputerDevices_OCTO_TESTING_v1.0.0.0.zip)

**Comment by dreckbaer** [comment]
Hi. Thx for the your help and the file. 
Sadly FanControl gives me "An unexpected error occured" and does not start. I attached the log file. 
Without the DLLs in /Plugins FanControl starts up without any issue. (I tried it with Aqua Computer Service running and without having it enabled in the background.) 
I use the HighFlow Next and the Octo in my PC.
Octo firmware is v1019. HFN firmware v1016.

Please let me know if I can help with anything else! 
[log.txt](https://github.com/medevil84/FanControl.AquacomputerDevices/files/11240802/log.txt)

**Comment by medevil84** [comment]
Ok, I think i've found the error, please try with the newer attached version and let me know if it works.
[FanControl.AquacomputerDevices_OCTO_TESTING_v1.0.0.1.zip](https://github.com/medevil84/FanControl.AquacomputerDevices/files/11242519/FanControl.AquacomputerDevices_OCTO_TESTING_v1.0.0.1.zip)

**Comment by dreckbaer** [comment]
Hi. 
Sorry, but its not working just yet. Same "unexpected error occured" message and FanControl refuses to start. 
I think the log shows more info this time around. 
Thx for your effort!

[log.txt](https://github.com/medevil84/FanControl.AquacomputerDevices/files/11242593/log.txt)

**Comment by medevil84** [comment]
Newer version, this hopefully should work: 
[FanControl.AquacomputerDevices_OCTO_TESTING_v1.0.0.2.zip](https://github.com/medevil84/FanControl.AquacomputerDevices/files/11253921/FanControl.AquacomputerDevices_OCTO_TESTING_v1.0.0.2.zip)

**Comment by dreckbaer** [comment]
It IS working! **Thank you sooooo much!** 

I installed the plugin and FanControl started up without any errors and FanControl shows now "Octo Controller Power" cards 1 to 8. I could manually match all the fans to the Octo. **All the fans attached to the Octo can now be controlled with FanControl!** 

![grafik](https://user-images.githubusercontent.com/13910970/232590285-c77cad4c-585e-492e-9795-12f32f662fb9.png)

I tried the "assisted setup" option and here I got a few errors. 
With "assisted setup" only "Octo Controller Power 1" has been detected. All other "Octo Controller Power" did not respond. 
I attached you the log file in case you are interested. 
--> [log.txt](https://github.com/medevil84/FanControl.AquacomputerDevices/files/11254946/log.txt)

A few more things that I noticed:

> 1. The plugin can/ does not read the values from the temperature sensors attached to the Octo. (NOT IMPORTANT!)

**Not true! I found the temperature readings in the drop down menu creating a curve.** Its just not visible as cards on the main screen.

2. I have a card that says "Octo Flow Sensor" that shows "50.5 rpm" - which actually is the sensor reading of the High Flow Next. (I just renamed it.)

**Comment by medevil84** [comment]
> 2\. I have a card that says "Octo Flow Sensor" that shows "50.5 rpm" - which actually is the sensor reading of the High Flow Next. (I just renamed it.)

I have found the issue and modified the relevant code, I'll release a new version that has official support for the octo device. Thanks for the debugging 👍

**Comment by medevil84** [comment]
Released version v1.0.0.3 with official Octo support. Please feel free to submit a new issue if you find any other problem :)

**Comment by dreckbaer** [comment]
I tested the v1.0.0.3 with the Octo and did not encounter any issues except the "assisted setup" errors I mentioned in my previous post! Thx again for your effort!
