### ISSUE TITLE
Two HighFlowNext in same system?

### ISSUE THREAD

**Issue by Tech127x** [medevil84/FanControl.AquacomputerDevices#4]
I have two highflow next devices in my PC.  I have a loop for the GPU and one for the CPU and there is one on each loop.  Based on temperatures reported, I would expect the fan stack for CPU and the one for the GPU to run at different speeds as they are different temperatures.  The issue I'm having is the system likes to change them both to the same sensor.  I can manually change them to the correct sensors, but Fancontrol only reads and sets curves to the lowest temp.  I jsut ran a few Cinebench, the CPU water hit 33c and the GPU was at 26c.  ALL fans were at the same speed for the lower temp.  What am I missing??
[log.txt](https://github.com/medevil84/FanControl.AquacomputerDevices/files/12115478/log.txt)

**Comment by medevil84** [comment]
Thanks for pointing out the issue, this need some major work since I didn't consider having two device of the same type, but will fix as soon as possible :)

**Comment by Tech127x** [comment]
Awesome!  Thank you sooo much!!!

**Comment by Tech127x** [comment]
Damn man, that was fast AF.  Works perfectly.  Excellent job and thank you!!
