### ISSUE TITLE
Defective download package

### ISSUE THREAD

**Issue by rony-x2** [medevil84/FanControl.AquacomputerDevices#6]
Hello,
I think something went wrong in the last release when creating the download package :)
On the one hand a necessary .dll file is missing, as well as many other files and folders are included.

For me personally it caused a lot of confusion - only when I switched to a relaase before, everything was totally easy and worked :)

**Comment by medevil84** [comment]
Hi @rony-x2, thanks for noticing, I forgot to attach the binary to the release. It's fixed now.
