### ISSUE TITLE
Failing to control octo fans until reboot

### ISSUE THREAD

**Issue by noktulo** [medevil84/FanControl.AquacomputerDevices#7]
I've been having an issue where often FanControl will lock up after waking from sleep. If I force quit and restart FanControl, it correctly controls my pump through my motherboard, but the fans connected through my Octo refuse to respond and stay at a low speed even when set to 100%. A reboot will fix it.

Because it's just the Octo fans that refuse to work after restarting FanControl I'm thinking this is an issue with this plugin but I'm not sure. Any ideas?

Here's the log showing FanControl starting up and OctoDevice failing, and then showing it working correctly after a reboot:

> 6/12/2024 9:11:44 PM: AquacomputerPlugin: Initializing.
> 6/12/2024 9:11:44 PM: OctoDevice.AssignDevice(device: VendorID=0x0C70, ProductID=0xF011, Version=256, DevicePath=\\?\hid#vid_0c70&pid_f011&mi_01#8&23ed922c&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}, logger: FanControl.Domain.PluginLogger)
> 6/12/2024 9:11:45 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:45 PM: AquacomputerPlugin: Loading
> 6/12/2024 9:11:45 PM: AquacomputerPlugin: Loading device FanControl.AquacomputerDevices.Devices.OctoDevice with index: 0
> 6/12/2024 9:11:45 PM: OctoDevice.Load(_container: FanControl.Domain.BackendProviders.Plugin.PluginSensorsContainer, index = 0)
> 6/12/2024 9:11:46 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:47 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:47 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:47 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:47 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:47 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:47 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:47 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:47 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:47 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:47 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:47 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:47 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:47 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:47 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:47 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:47 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:48 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:48 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:48 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:48 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:48 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:49 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:49 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:49 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:49 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:49 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:50 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:50 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:50 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:50 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:50 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:51 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:51 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:51 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:51 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:51 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:52 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:52 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:52 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:52 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:52 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:53 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:53 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:53 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:53 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:53 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:54 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:54 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:54 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:54 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:54 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:55 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:55 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:55 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:55 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:55 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:56 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:56 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:56 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:56 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:56 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:57 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:57 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:57 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:57 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:57 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:58 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:58 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:58 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:58 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:58 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:59 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:59 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:59 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:59 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:11:59 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:00 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:00 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:00 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:00 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:00 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:01 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:01 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:01 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:01 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:01 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:02 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:02 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:02 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:02 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:02 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:03 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:03 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:03 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:03 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:03 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:04 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:04 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:04 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:04 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:04 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:05 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:05 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:05 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:05 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:05 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:06 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:08 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:08 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:08 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:08 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:08 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:08 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:08 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:08 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:08 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:08 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:08 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:08 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:08 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:08 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:09 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:09 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:09 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:09 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:09 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:10 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:10 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:10 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:10 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:10 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:11 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:11 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:11 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:11 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:11 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:12 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:12 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:12 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:12 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:12 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:13 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:13 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:13 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:13 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:13 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:14 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:14 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:14 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:14 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:14 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:15 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:15 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:15 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:15 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:15 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:16 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:16 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:17 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:17 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:17 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:17 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:17 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:17 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:17 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:17 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:18 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:18 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:18 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:18 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:18 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:19 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:19 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:19 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:19 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:19 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:20 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:20 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:20 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:20 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:20 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:21 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:21 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:21 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:21 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:21 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:22 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:22 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:22 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:22 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:22 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:23 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:23 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:23 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:23 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:23 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:24 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:24 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:24 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:24 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:24 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:25 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:25 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:25 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:25 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:25 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:26 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:26 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:26 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:26 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:26 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:27 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:27 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:27 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:27 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:27 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:28 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:28 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:28 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:28 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:28 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:29 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:29 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:29 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:29 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:29 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:30 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:30 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:30 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:30 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:30 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:31 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:31 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:31 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:31 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:31 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:32 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:32 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:32 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:32 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:32 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:33 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:33 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:33 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:33 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:33 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:34 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:34 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:34 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:34 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:34 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:35 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:35 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:35 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:35 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:35 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:36 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:36 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:36 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:36 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:36 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:37 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:37 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:37 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:37 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:37 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:38 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:38 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:38 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:38 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:38 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:39 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:39 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:39 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:39 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:39 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:40 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:40 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:40 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:40 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:40 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:41 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:41 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:41 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:41 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:41 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:42 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:42 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:42 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:42 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:42 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:43 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:43 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:43 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:43 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:43 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:44 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:44 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:44 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:44 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:44 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:45 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:45 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:45 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:45 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:45 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:46 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:46 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:46 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:46 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:46 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:47 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:47 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:47 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:47 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:47 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:48 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:48 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:48 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:48 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:48 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:48 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:48 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:48 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:48 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:48 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:48 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:48 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:48 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:48 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:48 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:48 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:48 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:48 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:48 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:48 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:48 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:48 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:48 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:48 PM: OctoDevice: Failed to read settings from device.
> 6/12/2024 9:12:48 PM: AquacomputerPlugin: Closing.
> 6/12/2024 9:12:48 PM: OctoDevice.Unload()
> 6/12/2024 9:14:49 PM: AquacomputerPlugin: Initializing.
> 6/12/2024 9:14:49 PM: OctoDevice.AssignDevice(device: VendorID=0x0C70, ProductID=0xF011, Version=256, DevicePath=\\?\hid#vid_0c70&pid_f011&mi_01#8&23ed922c&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}, logger: FanControl.Domain.PluginLogger)
> 6/12/2024 9:14:49 PM: AquacomputerPlugin: Loading
> 6/12/2024 9:14:49 PM: AquacomputerPlugin: Loading device FanControl.AquacomputerDevices.Devices.OctoDevice with index: 0
> 6/12/2024 9:14:50 PM: OctoDevice.Load(_container: FanControl.Domain.BackendProviders.Plugin.PluginSensorsContainer, index = 0)

**Comment by medevil84** [comment]
Plese check latest version (1.0.0.7), should resolve this issue.
