### ISSUE TITLE
aquacomputer farbwerk 360 support

### ISSUE THREAD

**Issue by Betalos** [medevil84/FanControl.AquacomputerDevices#8]
Hello guys,

I installed the plugin, and somehow I only get the warning  **'Aquacomputer Devices could not initialize or has no sensors'**,
I am missing something here ?

**Comment by medevil84** [comment]
Sorry for the late reply. Unfortunately, I don't have a farberk 360 device, and the code for this device has been written by [@thomasfifer](https://github.com/thomasfifer) so i don't really know how does the device works. Can you try to upload the log file inside the fancontrol directory?

**Comment by Betalos** [comment]
@medevil84 Sorry for the late reply, turned out I have a farbwerk not farbwerk360 (two defirent devices), LibreHardware has a support for it , but it's not working (the temp sensor will be stuck at some value, also the read value is late). I'll make an pull request for this device since I think I got it working (had to reopen the stream on each update).

**Comment by Betalos** [comment]
Just to follow up, I decided to make an PR for the libreHardwareMonitor for the fix, since they already have the support for farbwek. So I'll close this one.
